apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aleph-validator-node-data-pvc
spec:
  storageClassName: topolvm-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
